#!/bin/bash
#SBATCH -t 2:00:00
#SBATCH -N 1 
#SBATCH --ntasks-per-node 96
#SBATCH -p standard96
#SBATCH -A hhpnhytt

module load gcc/9.2.0 openmpi/gcc.9/2.1.6 fftw3/ompi/gcc/3.3.8 nfft/gcc/3.5.1 anaconda3/2019.10 hdf5/gcc.8/1.10.5
export SLURM_CPU_BIND=none
export I_MPI_PIN_RESPECT_CPUSET=off
export I_MPI_DEBUG=6
export MKL_SERIAL=yes
export MKL_NUM_THREADS=1
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1

mpirun -np 96 /home/hhpnhytt/w2dynamics/DMFT.py 
